### ISSUE TITLE
Not working in 1.21.1

### ISSUE THREAD

**Issue by ItzXPurpleX** [DrakePork/RegionTeleport#7]
Plugin does not load in 1.21.1. 

[07:10:50 INFO]: [RegionTeleport] Enabling RegionTeleport v4.0.0
[07:10:50 ERROR]: Error occurred while enabling RegionTeleport v4.0.0 (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
        at RegionTeleport.jar/com.github.drakepork.regionteleport.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:172) ~[RegionTeleport.jar:?]
        at RegionTeleport.jar/com.github.drakepork.regionteleport.commandapi.CommandAPI.onEnable(CommandAPI.java:135) ~[RegionTeleport.jar:?]
        at RegionTeleport.jar/com.github.drakepork.regionteleport.RegionTeleport.onEnable(RegionTeleport.java:85) ~[RegionTeleport.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by DrakePork** [comment]
This is now fixed on the [latest release](https://modrinth.com/plugin/regionteleport/version/4.0.1)
